### ISSUE TITLE
Making nav_only map dynamic

### ISSUE THREAD

**Issue by wsneijers** [minhtrietdiep/ESA-PROJ#16]
Rewrite nav_only launchfile to accept map parameter.

**Comment by wsneijers** [comment]
Also rewrite **using map** part of [Map Server ](https://github.com/minhtrietdiep/ESA-PROJ/wiki/Map-Server) when doing so.

**Comment by MrJaeqx** [comment]
Also move maps from faw/map to maps folder

**Comment by wsneijers** [comment]
Fixed by rewriting launch file structure
