### ISSUE TITLE
Eth0 without root doesn't work

### ISSUE THREAD

**Issue by ticolaugs** [minhtrietdiep/ESA-PROJ#48]
In the [Robot controller OS setup](https://github.com/FontysAtWork/ESA-PROJ/wiki/Robot-controller-setup) part of the [wiki](https://github.com/FontysAtWork/ESA-PROJ/wiki) the last step is to setup the etherCAT connection. the two commands given there don't seem to work (tested by 2 different people on 2 different devices to be sure), after some searching what does seem to work is to go into the youbot-ethercat.cfg file and change the EthernetDevice (2nd line) from eth0 to whatever your device has as an Ethernet interface (in my case enp3s0 or enp2s5 depending on the device). this can be found by typing ifconfig into the terminal. maybe it is a good idea to add this to the wiki seeing as this will always work and the two commands won't (in my experience).

ps. finding out these two commands haven't worked is when running the launch files it gives an error that it can't connect to EtherCAT.

**Comment by wsneijers** [comment]
Sorry for the inconvenience. The two commands you mentioned were for Ubuntu 14.04 (I assume you're using 16.04). We also noticed the network interface name changes from 14.04 to 16.04. It is indeed possible to change the name in the youbot-ethercat.cfg file. Do keep in mind that changing it means you can no longer use it on 14.04 (unless you change it back off course). What we did was configure Ubuntu to use the old interface names. A quick google on _Ubuntu ens33 to eth0_ should get you started.

**Comment by ticolaugs** [comment]
okay thank you.
